module.exports = {
    emailAddressText: '//*[contains (text(),"Email address")]',
    emailAddressTextBox: '//*[@id="text-field-identifier"]',
    continueButton: '//*[contains (text(),"Continue")]',
    emailAddressPageLocator: '//div[@class="cl-component cl-sign-in"]',
    checkEmailText: '//*[contains (text(),"Check your email")]',
    tryAnotherMethodHyperLink: '//*[@class="cl-auth-form-footer"]/button',
    welcomePage: '//*[@class="PG_RoBWBYRyyIjVtW7Fp"]',
    errorMessageAfterOtpFailed: '//*[contains(text(),"The verification strategy is not valid for this account")]',
    otpTextBox1: '//*[@data-test-id="otp-container"]//input[1]',
    otpTextBox2: '//*[@data-test-id="otp-container"]//input[2]',
    otpTextBox3: '//*[@data-test-id="otp-container"]//input[3]',
    otpTextBox4: '//*[@data-test-id="otp-container"]//input[4]',
    otpTextBox5: '//*[@data-test-id="otp-container"]//input[5]',
    otpTextBox6: '//*[@data-test-id="otp-container"]//input[6]',
    dashBoardText: '//*[@data-testid="page-heading-Dashboard"]/ul/h2',
    emailCodeButton: '//*[@class="cl-auth-form-body cl-auth-form-body-compact"]/button[2]',
    reimbursements: '//p[contains(text(),"Reimbursements")]',
    myReimbursementsPageTitleText: '//h2[contains(text(),"My reimbursements")]',
    myExpensesText: '//p[contains (text(),"My expenses")]',
    newExpensesButton: '//button[@class="chakra-button css-meloq6"]',
    expensesDetailsTitleText: '//h2[contains(text(),"Expense details")]',
    merchantText: "//h2[contains(text(),'Merchant')]",
    merchantNameTextBox: '//input[@id="merchantName"]',
    enterAmountTextBox: '//input[@id="amount"]',
    amountText: "//h2[contains(text(),'Amount')]",
    currencyText: "//label[contains(text(),'Currency')]",
    currencyDropDown: '(//button[@data-testid="undefined-select-button"])[1]',
    errorMessageText: '(//div[@class="chakra-form__error-message css-1toecx"])[1]',
    selectTheUAE: '(//ul[@role="listbox"]//li)[1]',
    chooseTheCategory: '(//div[@aria-haspopup="dialog"])[2]//button',
    closeButtonUnderMyExpenses: '//button[@aria-label="Close"]',
    addCategory: '//ul[@role="listbox"]//li[4]',
    fullCalender: '//button[@class="chakra-button css-139s4za"]',
    closeTheWelcomePage: '//*[@aria-label="Close"]',
    downLoadButton: '//button[contains(text(),"Download")]',
    approvalGroupFelid: '(//button[@type="button"]//p)[4]',
    addMessage: '//textarea[@id="additionalInfo"]',
    submitExpensesButton: '//button[contains(text(),"Submit expense")]',
    successFullMessage: '//*[contains(text(),"Expense submitted")]',
    addYesterDayDate: '(//*[@class="css-1iue6md"])[2]',
    searchInputBox: '//input[@class="chakra-input css-6izj5n"]',
    filterButton: '//button[@class="chakra-button css-113vb34"]',
    filterTextVerify: '//h2[contains (text(),"Filters")]',
    categoryTextBox: '//input[@class="chakra-input css-14wwxbh"]',
    cashDisbursement: '//p[contains(text(),"Cash disbursement")]',
    searchElementIndex: '(//p[@class="chakra-text css-1tj5cdk"])[1]',
    allButton: '//p[contains(text(),"All")]',
    tableVisible: '//div[@class="chakra-table css-16b2j6r"]',
    closeUnderTheImageRemove: '(//div[@class="chakra-fade"])[2]',
    imageAddButton: '//button[@class="chakra-button css-11h6ew5"]',
    checkBoxFirstExpenses: '(//label[@title="Toggle Row Selected"]//input)[1]',
    afterCheckTheBox: '(//span[@aria-hidden="true"])[2]',
    draftSection: '(//div[@class="css-1y2ag93"])[2]',
    expensesAmountText: '(//div[@role="cell"])[6]',
    tableValueDataIsVisible: '//div[@class="css-i9gxme"]',
    submittedSection: '(//div[@class="css-1y2ag93"])[3]',
    totalAmountErrorMessage: '//*[contains(text(),"Total amount must be greater than 0")]',
    submittedTable: '//div[@class="css-i9gxme"]',
    totalAmountValue: '//div[@class="css-158123l"]//div',
    approvedSection: '(//div[@class="css-1y2ag93"])[4]',
    rejectedSection: '(//div[@class="css-1y2ag93"])[5]',
    ReimbursedSection: '(//div[@class="css-1y2ag93"])[6]',
    draftSection: '(//div[@class="css-1y2ag93"])[2]',
    idAndInCurredTable: '//div[contains(text(),"ID/Incurred at")]',
    selectSearchId: '(//div[@class="css-1nkzjh8"])[1]',
    statusSection: '//div[@class="css-173ehs6"]',
    addCurrency: '(//button[@class="chakra-button css-1vq5ze8"])[1]',
    activityLogTab: '(//button[@class="chakra-button css-1r5urv2"])[2]',
    submittedExpensesText: "//div[@class='chakra-stack css-9ebre5']/p[contains(text(),'Expense was submitted on')]",
    verifyTodayText: '//h2[contains(text(),"Today")]',
    commentBox: '//*[@id="comment"]',
    approvedTab: '(//p[@class="chakra-text css-1xkw4j8"])[4]',
    commentSend: '//button[@class="chakra-button css-11mq1ic"]',
    expensesAmountTab: '//div[@class="css-1t30m9j"][2]',
    statusTab: '//div[contains(text(),"Status")]',
    rejectedTab: '(//div[@class="css-1y2ag93"])[5]',
    fileUpload: '(//div[@role="presentation"]//input)[2]',
    fileUploadElement: '//div[@role="presentation"]//input',
}